apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-users
spec:
  replicas: 
  selector:
    matchLabels:
      app: ibm-users
  template:
    metadata:
      labels:
        app: ibm-users
    spec:
      containers:
      - name: ibm-users
        image: us.icr.io/carlos14/us.icr.io/carlos14/ibm-users:3-main-18825daf-20220406231558
